
export enum ModalIDs {
    matterDetails = 'Matter Details',
    addAdjustment = 'Add Adjustment',

    contractPrice = 'Contract Price',
    releaseFee = 'Release Fee',
    waterUsage = 'Water Usage',
    councilRates = 'Council Rates',
    waterAccessFee = 'Water Access Fee',
    sewerageAccessFee = 'Sewerage Access Fee',
    administrationFund = 'Administration Fund',
    sinkingFund = 'Sinking Fund',
    insurance = 'Insurance',
    penaltyInterest = 'Penalty Interest',
    otherAdjustment = 'Other Adjustment',
    otherAdjustmentDate = 'Other Adjustment Date',
    strataLevies = 'Strata Levies',
    waterDrainageFee = 'Water Drainage Fee',
    parksCharge = 'Parks Charge',
    waterServiceCharge = 'Water Service Charge',
    sewerageUsage = 'Sewerage Usage',
    maintenanceFund = 'Maintenance Fund',
    landTax = 'Land Tax',
    rent = 'Rent',
    ownersCorporationFees = 'Owners Corporation Fees',
    councilRatesChargesLevies = 'Council Rates, Charges, Levies',
    waterRatesChargesLevies = 'Water Rates, Charges & Levies',
    sewerageServiceCharge = 'Sewerage Service Charge',
    ownersAdministrationFundFee = 'Owners Corporation - Administration Fund Fee',
    ownersMaintenanceFundFee = 'Owners Corporation - Maintenance Fund Fee',
    ownersSinkingFundFee = 'Owners Corporation - Sinking Fund Fee',
    ownersInsurance = 'Owners Corporation - Insurance',
    waterSewerageRates = 'Water/Sewerage Rates',
    emergencyServicesLevy = 'Emergency Services Levy',
    waterAndSewerageRates = 'Water and Sewerage Rates',

    fee = 'Fee',
    additionalRequirements = 'Additional Requirements',
    payeeDetails = 'Cheque Payee',
    ourRequirements = 'Our Requirements'
}