
export const GET_DATA_FROM_ACTIONSTEP_REQUESTED = "PexaReducer/GET_DATA_FROM_ACTIONSTEP_REQUESTED";
export const GET_DATA_FROM_ACTIONSTEP_SUCCESS = "PexaReducer/GET_DATA_FROM_ACTIONSTEP_SUCCESS";
export const GET_DATA_FROM_ACTIONSTEP_FAILED = "PexaReducer/GET_DATA_FROM_ACTIONSTEP_FAILED";

export const SET_PEXA_WORKSPACE_CREATION_REQUEST = "PexaReducer/SET_PEXA_WORKSPACE_CREATION_REQUEST"

export const VALIDATE_LAND_TITLE_REQUESTED = "PexaReducer/VALIDATE_LAND_TITLE_REQUESTED"
export const VALIDATE_LAND_TITLE_SUCCESS = "PexaReducer/VALIDATE_LAND_TITLE_SUCCESS"
export const VALIDATE_LAND_TITLE_FAILED = "PexaReducer/VALIDATE_LAND_TITLE_FAILED"

export const GET_PEXA_WORKSPACE_SUMMARY_REQUESTED = "PexaReducer/GET_PEXA_WORKSPACE_SUMMARY_REQUESTED"
export const GET_PEXA_WORKSPACE_SUMMARY_SUCCESS = "PexaReducer/GET_PEXA_WORKSPACE_SUMMARY_SUCCESS"
export const GET_PEXA_WORKSPACE_SUMMARY_FAILED = "PexaReducer/GET_PEXA_WORKSPACE_SUMMARY_FAILED"

export const GET_AVAILABLE_SETTLEMENT_TIMES_REQUESETD = "PexaReducer/GET_AVAILABLE_SETTLEMENT_TIMES_REQUESETD"
export const GET_AVAILABLE_SETTLEMENT_TIMES_SUCCESS = "PexaReducer/GET_AVAILABLE_SETTLEMENT_TIMES_SUCCESS"
export const GET_AVAILABLE_SETTLEMENT_TIMES_FAILED = "PexaReducer/GET_AVAILABLE_SETTLEMENT_TIMES_FAILED"

export const SEND_DATA_TO_PEXA_REQUESTED = "PexaReducer/SEND_DATA_TO_PEXA_REQUESTED";
export const SEND_DATA_TO_PEXA_SUCCESS = "PexaReducer/SEND_DATA_TO_PEXA_SUCCESS";
export const SEND_DATA_TO_PEXA_FAILED = "PexaReducer/SEND_DATA_TO_PEXA_FAILED";

export const CREATE_INVITATION_REQUESTED = "PexaReducer/CREATE_INVITATION_REQUESTED";
export const CREATE_INVITATION_SUCCESS = "PexaReducer/CREATE_INVITATION_SUCCESS";
export const CREATE_INVITATION_FAILED = "PexaReducer/CREATE_INVITATION_FAILED";

export const SAVE_PEXA_FORM_DATA = "PexaReducer/SAVE_PEXA_FORM_DATA";
export const CLEAR_PEXA_FORM_DATA = "PexaReducer/CLEAR_PEXA_FORM_DATA"

export const CLEAR_PEXA_STATE = "PexaReducer/CLEAR_PEXA_STATE";