openapi: 3.0.0
components:
  schemas:
    FullName:
      type: object
      required:
        - GivenName
      maximum: 1
      minimum: 0
      properties:
        NameTitle:
          type: string
          enum:
            - ABBOT
            - AB
            - ADML
            - ACM
            - AIRCDRE
            - AM
            - AVM
            - AC
            - ACW
            - ALD
            - AMBSR
            - ARCHBISHOP
            - ARCHDEACON
            - ASSOC PROF
            - BARON
            - BARONESS
            - BISHOP
            - BDR
            - BRIG
            - BR
            - CDT
            - CANON
            - CAPT
            - CARDNL
            - CHAP
            - CPO
            - COL
            - CMDR
            - CMM
            - CDRE
            - CONST
            - CONSUL
            - CPL
            - COUNT
            - COUNTESS
            - DAME
            - DEACON
            - DEACONESS
            - DEAN
            - DEPUTY SUPT
            - DIRECTOR
            - DR
            - EARL
            - ENGR
            - FR
            - FLTLT
            - FSGT
            - FLGOFF
            - GEN
            - GOV
            - GP CAPT
            - HON
            - JUDGE
            - JUSTICE
            - LADY
            - LBDR
            - LCPL
            - LAC
            - LACW
            - LS
            - LT
            - LEUT
            - LTCOL
            - LTCDR
            - LTGEN
            - LTGOV
            - LORD
            - MADAM
            - MADAME
            - MAJ
            - MAJGEN
            - MGR
            - MSTR
            - MAYOR
            - MAYORESS
            - MIDN
            - MISS
            - MR
            - MON
            - MOST REV
            - MTHR
            - MRS
            - MS
            - NURSE
            - OCDT
            - PASTOR
            - PO
            - PLTOFF
            - PTE
            - PROF
            - RABBI
            - RADM
            - RECTOR
            - RSM-A
            - REV
            - RTHON
            - RT REV
            - SMN
            - 2LT
            - SEN
            - SNR
            - SGT
            - SIR
            - SR
            - SISTER SUP
            - SQNLDR
            - SCDT
            - SSGT
            - SM
            - SBLT
            - UPT
            - SWAMI
            - VADM
            - VCE CMNDR
            - VISCOUNT
            - WOFF
            - WO
            - WO1
            - WO2
            - WOFF-AF
            - WO-N
            - WCDR
        GivenName:
          type: array
          minItems: 1
          items:
            type: object
            properties:
              order:
                type: integer
                xml:
                  attribute: true
        FamilyName:
          type: string
          example: John
        FamilyNameOrder:
          type: string
          enum:
            - Last
            - First
        NameSuffix:
          type: string
          example: Jr
        DateOfBirth:
          type: string
          format: date
          example: '1960-03-01'
