//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace WCA.GlobalX.Client
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/version/2013/09/12")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://globalx.com.au/common/model/version/2013/09/12", IsNullable = false)]
    public partial class Version
    {

        private string modelVersionField;

        private string applicationNameField;

        private string applicationVersionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ModelVersion
        {
            get
            {
                return this.modelVersionField;
            }
            set
            {
                this.modelVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ApplicationName
        {
            get
            {
                return this.applicationNameField;
            }
            set
            {
                this.applicationNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ApplicationVersion
        {
            get
            {
                return this.applicationVersionField;
            }
            set
            {
                this.applicationVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/matter/2013/07/31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://globalx.com.au/common/model/matter/2013/07/31", IsNullable = false)]
    public partial class Matter
    {

        private string matterReferenceField;

        private Entity matterEntityField;

        private Relationship[] relatedEntitiesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MatterReference
        {
            get
            {
                return this.matterReferenceField;
            }
            set
            {
                this.matterReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Entity MatterEntity
        {
            get
            {
                return this.matterEntityField;
            }
            set
            {
                this.matterEntityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
        public Relationship[] RelatedEntities
        {
            get
            {
                return this.relatedEntitiesField;
            }
            set
            {
                this.relatedEntitiesField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Aircraft))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Watercraft))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MotorVehicle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecuredPartyGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CollateralRegistration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealProperty))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Individual))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organisation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Company))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Settlement))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public abstract partial class Entity
    {

        private Relationship[] relationshipsField;

        private Datum[] otherDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 0)]
        public Relationship[] Relationships
        {
            get
            {
                return this.relationshipsField;
            }
            set
            {
                this.relationshipsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 1)]
        public Datum[] OtherData
        {
            get
            {
                return this.otherDataField;
            }
            set
            {
                this.otherDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Relationship
    {

        private string relationshipTypeField;

        private Entity entityField;

        private RelationshipInformation informationField;

        /// <remarks/>
        public string RelationshipType
        {
            get
            {
                return this.relationshipTypeField;
            }
            set
            {
                this.relationshipTypeField = value;
            }
        }

        /// <remarks/>
        public Entity Entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public RelationshipInformation Information
        {
            get
            {
                return this.informationField;
            }
            set
            {
                this.informationField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistrationHistoryInformation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShareholderInformation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public abstract partial class RelationshipInformation
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class RegistrationHistoryInformation : RelationshipInformation
    {

        private System.DateTime changeTimeField;

        private CollateralChangeType changeTypeField;

        /// <remarks/>
        public System.DateTime ChangeTime
        {
            get
            {
                return this.changeTimeField;
            }
            set
            {
                this.changeTimeField = value;
            }
        }

        /// <remarks/>
        public CollateralChangeType ChangeType
        {
            get
            {
                return this.changeTypeField;
            }
            set
            {
                this.changeTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public enum CollateralChangeType
    {

        /// <remarks/>
        Create,

        /// <remarks/>
        Amend,

        /// <remarks/>
        Discharge,

        /// <remarks/>
        Remove,

        /// <remarks/>
        Reinstate,

        /// <remarks/>
        AddressForServiceChange,

        /// <remarks/>
        Transfer,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class ShareholderInformation : RelationshipInformation
    {

        private System.Nullable<int> numberOfSharesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> NumberOfShares
        {
            get
            {
                return this.numberOfSharesField;
            }
            set
            {
                this.numberOfSharesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Datum
    {

        private string keyField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Aircraft : Entity
    {

        private string manufacturersNumberField;

        private string manufacturersNameField;

        private string modelDesignatorField;

        private string nationalityCodeField;

        private string nationalityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string ManufacturersNumber
        {
            get
            {
                return this.manufacturersNumberField;
            }
            set
            {
                this.manufacturersNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string ManufacturersName
        {
            get
            {
                return this.manufacturersNameField;
            }
            set
            {
                this.manufacturersNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string ModelDesignator
        {
            get
            {
                return this.modelDesignatorField;
            }
            set
            {
                this.modelDesignatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public string NationalityCode
        {
            get
            {
                return this.nationalityCodeField;
            }
            set
            {
                this.nationalityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string Nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Watercraft : Entity
    {

        private string hINField;

        private string officialNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string HIN
        {
            get
            {
                return this.hINField;
            }
            set
            {
                this.hINField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string OfficialNumber
        {
            get
            {
                return this.officialNumberField;
            }
            set
            {
                this.officialNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class MotorVehicle : Entity
    {

        private string vINField;

        private string chassisField;

        private string manufacturersNumberField;

        private string makeField;

        private string modelField;

        private string yearField;

        private string stateField;

        private string seriesField;

        private string bodyField;

        private string gradeField;

        private string cylindersField;

        private string versionField;

        private string numberPlateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string VIN
        {
            get
            {
                return this.vINField;
            }
            set
            {
                this.vINField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string Chassis
        {
            get
            {
                return this.chassisField;
            }
            set
            {
                this.chassisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string ManufacturersNumber
        {
            get
            {
                return this.manufacturersNumberField;
            }
            set
            {
                this.manufacturersNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public string Make
        {
            get
            {
                return this.makeField;
            }
            set
            {
                this.makeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string Model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public string Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
        public string Series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 8)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 9)]
        public string Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 10)]
        public string Cylinders
        {
            get
            {
                return this.cylindersField;
            }
            set
            {
                this.cylindersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 11)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 12)]
        public string NumberPlate
        {
            get
            {
                return this.numberPlateField;
            }
            set
            {
                this.numberPlateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class SecuredPartyGroup : Entity
    {

        private string spgNumberField;

        private string spgAccessCodeField;

        private System.Nullable<System.DateTime> ppsrCreatedDateField;

        private string nameField;

        private Address[] addressesField;

        private ContactDetails contactDetailsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string SpgNumber
        {
            get
            {
                return this.spgNumberField;
            }
            set
            {
                this.spgNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string SpgAccessCode
        {
            get
            {
                return this.spgAccessCodeField;
            }
            set
            {
                this.spgAccessCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public System.Nullable<System.DateTime> PpsrCreatedDate
        {
            get
            {
                return this.ppsrCreatedDateField;
            }
            set
            {
                this.ppsrCreatedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 4)]
        public Address[] Addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public ContactDetails ContactDetails
        {
            get
            {
                return this.contactDetailsField;
            }
            set
            {
                this.contactDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Address
    {

        private string addressTypeField;

        private string unitField;

        private string levelField;

        private string numberField;

        private string streetField;

        private string streetTypeField;

        private string localityField;

        private System.Nullable<State> stateField;

        private string postcodeField;

        private string countryField;

        private string parishField;

        private string sectionField;

        private string townField;

        private string countyField;

        private string buildingNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AddressType
        {
            get
            {
                return this.addressTypeField;
            }
            set
            {
                this.addressTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StreetType
        {
            get
            {
                return this.streetTypeField;
            }
            set
            {
                this.streetTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<State> State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Parish
        {
            get
            {
                return this.parishField;
            }
            set
            {
                this.parishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Section
        {
            get
            {
                return this.sectionField;
            }
            set
            {
                this.sectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Town
        {
            get
            {
                return this.townField;
            }
            set
            {
                this.townField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BuildingName
        {
            get
            {
                return this.buildingNameField;
            }
            set
            {
                this.buildingNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public enum State
    {

        /// <remarks/>
        Unknown,

        /// <remarks/>
        NSW,

        /// <remarks/>
        QLD,

        /// <remarks/>
        Vic,

        /// <remarks/>
        Tas,

        /// <remarks/>
        ACT,

        /// <remarks/>
        WA,

        /// <remarks/>
        NT,

        /// <remarks/>
        SA,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class ContactDetails
    {

        private string emailAddressField;

        private string contactNameField;

        private PhoneNumber[] phoneNumbersField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ContactName
        {
            get
            {
                return this.contactNameField;
            }
            set
            {
                this.contactNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public PhoneNumber[] PhoneNumbers
        {
            get
            {
                return this.phoneNumbersField;
            }
            set
            {
                this.phoneNumbersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class PhoneNumber
    {

        private System.Nullable<PhoneNumberKind> phoneNumberKindField;

        private string numberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<PhoneNumberKind> PhoneNumberKind
        {
            get
            {
                return this.phoneNumberKindField;
            }
            set
            {
                this.phoneNumberKindField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public enum PhoneNumberKind
    {

        /// <remarks/>
        Contact,

        /// <remarks/>
        Home,

        /// <remarks/>
        Work,

        /// <remarks/>
        Mobile,

        /// <remarks/>
        Fax,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class CollateralRegistration : Entity
    {

        private string registeredIdentifierField;

        private string registeredIdentifierTypeField;

        private string registrationNumberField;

        private System.Nullable<System.DateTime> registrationChangeTimeField;

        private System.Nullable<System.DateTime> registrationStartTimeField;

        private System.Nullable<System.DateTime> registrationEndTimeField;

        private string registrationTokenField;

        private string linkedRegistrationNumberField;

        private System.Nullable<CollateralType> collateralTypeField;

        private System.Nullable<CollateralCategory> collateralCategoryField;

        private System.Nullable<CollateralClass> collateralClassField;

        private bool collateralClassFieldSpecified;

        private string collateralSubclassField;

        private string givingOfNoticeIdentifierField;

        private System.Nullable<bool> isInventoryField;

        private System.Nullable<bool> isTransitionalField;

        private System.Nullable<bool> isSubjectToControlField;

        private System.Nullable<bool> isSubordinateField;

        private System.Nullable<bool> isPurchaseMoneySecurityInterestField;

        private bool isPurchaseMoneySecurityInterestFieldSpecified;

        private System.Nullable<bool> proceedsToBeClaimedField;

        private string proceedsDescriptionField;

        private string descriptionField;

        private Attachment[] attachmentsField;

        private System.Nullable<long> changeNumberField;

        private bool changeNumberFieldSpecified;

        private string givingOfNoticeIdentifier1Field;

        private System.Nullable<bool> isMigratedField;

        private bool isMigratedFieldSpecified;

        private string registrationKindField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string RegisteredIdentifier
        {
            get
            {
                return this.registeredIdentifierField;
            }
            set
            {
                this.registeredIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string RegisteredIdentifierType
        {
            get
            {
                return this.registeredIdentifierTypeField;
            }
            set
            {
                this.registeredIdentifierTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string RegistrationNumber
        {
            get
            {
                return this.registrationNumberField;
            }
            set
            {
                this.registrationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public System.Nullable<System.DateTime> RegistrationChangeTime
        {
            get
            {
                return this.registrationChangeTimeField;
            }
            set
            {
                this.registrationChangeTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public System.Nullable<System.DateTime> RegistrationStartTime
        {
            get
            {
                return this.registrationStartTimeField;
            }
            set
            {
                this.registrationStartTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public System.Nullable<System.DateTime> RegistrationEndTime
        {
            get
            {
                return this.registrationEndTimeField;
            }
            set
            {
                this.registrationEndTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
        public string RegistrationToken
        {
            get
            {
                return this.registrationTokenField;
            }
            set
            {
                this.registrationTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
        public string LinkedRegistrationNumber
        {
            get
            {
                return this.linkedRegistrationNumberField;
            }
            set
            {
                this.linkedRegistrationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 8)]
        public System.Nullable<CollateralType> CollateralType
        {
            get
            {
                return this.collateralTypeField;
            }
            set
            {
                this.collateralTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 9)]
        public System.Nullable<CollateralCategory> CollateralCategory
        {
            get
            {
                return this.collateralCategoryField;
            }
            set
            {
                this.collateralCategoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 10)]
        public System.Nullable<CollateralClass> CollateralClass
        {
            get
            {
                return this.collateralClassField;
            }
            set
            {
                this.collateralClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CollateralClassSpecified
        {
            get
            {
                return this.collateralClassFieldSpecified;
            }
            set
            {
                this.collateralClassFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 11)]
        public string CollateralSubclass
        {
            get
            {
                return this.collateralSubclassField;
            }
            set
            {
                this.collateralSubclassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 12)]
        public string GivingOfNoticeIdentifier
        {
            get
            {
                return this.givingOfNoticeIdentifierField;
            }
            set
            {
                this.givingOfNoticeIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 13)]
        public System.Nullable<bool> IsInventory
        {
            get
            {
                return this.isInventoryField;
            }
            set
            {
                this.isInventoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 14)]
        public System.Nullable<bool> IsTransitional
        {
            get
            {
                return this.isTransitionalField;
            }
            set
            {
                this.isTransitionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 15)]
        public System.Nullable<bool> IsSubjectToControl
        {
            get
            {
                return this.isSubjectToControlField;
            }
            set
            {
                this.isSubjectToControlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 16)]
        public System.Nullable<bool> IsSubordinate
        {
            get
            {
                return this.isSubordinateField;
            }
            set
            {
                this.isSubordinateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 17)]
        public System.Nullable<bool> IsPurchaseMoneySecurityInterest
        {
            get
            {
                return this.isPurchaseMoneySecurityInterestField;
            }
            set
            {
                this.isPurchaseMoneySecurityInterestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPurchaseMoneySecurityInterestSpecified
        {
            get
            {
                return this.isPurchaseMoneySecurityInterestFieldSpecified;
            }
            set
            {
                this.isPurchaseMoneySecurityInterestFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 18)]
        public System.Nullable<bool> ProceedsToBeClaimed
        {
            get
            {
                return this.proceedsToBeClaimedField;
            }
            set
            {
                this.proceedsToBeClaimedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 19)]
        public string ProceedsDescription
        {
            get
            {
                return this.proceedsDescriptionField;
            }
            set
            {
                this.proceedsDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 20)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 21)]
        public Attachment[] Attachments
        {
            get
            {
                return this.attachmentsField;
            }
            set
            {
                this.attachmentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 22)]
        public System.Nullable<long> ChangeNumber
        {
            get
            {
                return this.changeNumberField;
            }
            set
            {
                this.changeNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChangeNumberSpecified
        {
            get
            {
                return this.changeNumberFieldSpecified;
            }
            set
            {
                this.changeNumberFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GivingOfNoticeIdentifier", IsNullable = true, Order = 23)]
        public string GivingOfNoticeIdentifier1
        {
            get
            {
                return this.givingOfNoticeIdentifier1Field;
            }
            set
            {
                this.givingOfNoticeIdentifier1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 24)]
        public System.Nullable<bool> IsMigrated
        {
            get
            {
                return this.isMigratedField;
            }
            set
            {
                this.isMigratedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsMigratedSpecified
        {
            get
            {
                return this.isMigratedFieldSpecified;
            }
            set
            {
                this.isMigratedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public string RegistrationKind
        {
            get
            {
                return this.registrationKindField;
            }
            set
            {
                this.registrationKindField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public enum CollateralType
    {

        /// <remarks/>
        Commercial,

        /// <remarks/>
        Consumer,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public enum CollateralCategory
    {

        /// <remarks/>
        General,

        /// <remarks/>
        Intangible,

        /// <remarks/>
        Tangible,

        /// <remarks/>
        Financial,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public enum CollateralClass
    {

        /// <remarks/>
        MotorVehicle,

        /// <remarks/>
        Watercraft,

        /// <remarks/>
        Aircraft,

        /// <remarks/>
        AircraftEngine,

        /// <remarks/>
        Helicopter,

        /// <remarks/>
        SmallAircraft,

        /// <remarks/>
        Airframe,

        /// <remarks/>
        Agriculture,

        /// <remarks/>
        Crops,

        /// <remarks/>
        Livestock,

        /// <remarks/>
        OtherGoods,

        /// <remarks/>
        General,

        /// <remarks/>
        GeneralWithExceptions,

        /// <remarks/>
        Account,

        /// <remarks/>
        IntellectualProperty,

        /// <remarks/>
        CircuitLayout,

        /// <remarks/>
        Copyright,

        /// <remarks/>
        Design,

        /// <remarks/>
        Patent,

        /// <remarks/>
        TradeMark,

        /// <remarks/>
        PlantBreedersRight,

        /// <remarks/>
        GeneralIntangible,

        /// <remarks/>
        ChattelPaper,

        /// <remarks/>
        Currency,

        /// <remarks/>
        DocumentOfTitle,

        /// <remarks/>
        IntermediatedSecurity,

        /// <remarks/>
        InvestmentInstrument,

        /// <remarks/>
        NegotiableInstrument,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Attachment
    {

        private string fileNameField;

        private string descriptionField;

        private System.Nullable<long> idField;

        private bool idFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<long> Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class RealProperty : Entity
    {

        private Address addressField;

        private Location locationField;

        private string nameField;

        private string propertyTypeField;

        private string titleReferenceField;

        private LotPlan lotPlanField;

        private VolumeFolio volumeFolioField;

        private BodyCorporate bodyCorporateField;

        private Dealing[] dealingsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public Address Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public Location Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public string PropertyType
        {
            get
            {
                return this.propertyTypeField;
            }
            set
            {
                this.propertyTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string TitleReference
        {
            get
            {
                return this.titleReferenceField;
            }
            set
            {
                this.titleReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public LotPlan LotPlan
        {
            get
            {
                return this.lotPlanField;
            }
            set
            {
                this.lotPlanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
        public VolumeFolio VolumeFolio
        {
            get
            {
                return this.volumeFolioField;
            }
            set
            {
                this.volumeFolioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
        public BodyCorporate BodyCorporate
        {
            get
            {
                return this.bodyCorporateField;
            }
            set
            {
                this.bodyCorporateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 8)]
        public Dealing[] Dealings
        {
            get
            {
                return this.dealingsField;
            }
            set
            {
                this.dealingsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Location
    {

        private System.Nullable<decimal> longitudeField;

        private System.Nullable<decimal> latitudeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class LotPlan
    {

        private string lotField;

        private string sectionField;

        private string planTypeField;

        private string planNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Lot
        {
            get
            {
                return this.lotField;
            }
            set
            {
                this.lotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Section
        {
            get
            {
                return this.sectionField;
            }
            set
            {
                this.sectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PlanType
        {
            get
            {
                return this.planTypeField;
            }
            set
            {
                this.planTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PlanNumber
        {
            get
            {
                return this.planNumberField;
            }
            set
            {
                this.planNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class VolumeFolio
    {

        private string volumeField;

        private string folioField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Folio
        {
            get
            {
                return this.folioField;
            }
            set
            {
                this.folioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class BodyCorporate
    {

        private string ctsNumberField;

        private Individual managerField;

        private string buildingNameField;

        private Address[] addressesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CtsNumber
        {
            get
            {
                return this.ctsNumberField;
            }
            set
            {
                this.ctsNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Individual Manager
        {
            get
            {
                return this.managerField;
            }
            set
            {
                this.managerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BuildingName
        {
            get
            {
                return this.buildingNameField;
            }
            set
            {
                this.buildingNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public Address[] Addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Individual : Entity
    {

        private string surnameField;

        private string givenNamesField;

        private System.Nullable<System.DateTime> dateOfBirthField;

        private System.Nullable<System.DateTime> dateOfDeathField;

        private PreviousName[] previousNamesField;

        private Address[] addressesField;

        private Gender genderField;

        private ContactDetails contactDetailsField;

        public Individual()
        {
            this.genderField = Gender.NotSpecified;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string Surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string GivenNames
        {
            get
            {
                return this.givenNamesField;
            }
            set
            {
                this.givenNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public System.Nullable<System.DateTime> DateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public System.Nullable<System.DateTime> DateOfDeath
        {
            get
            {
                return this.dateOfDeathField;
            }
            set
            {
                this.dateOfDeathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 4)]
        public PreviousName[] PreviousNames
        {
            get
            {
                return this.previousNamesField;
            }
            set
            {
                this.previousNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 5)]
        public Address[] Addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        [System.ComponentModel.DefaultValueAttribute(Gender.NotSpecified)]
        public Gender Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 7)]
        public ContactDetails ContactDetails
        {
            get
            {
                return this.contactDetailsField;
            }
            set
            {
                this.contactDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class PreviousName
    {

        private string surnameField;

        private string givenNamesField;

        private System.Nullable<System.DateTime> endDateField;

        private string nameTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string GivenNames
        {
            get
            {
                return this.givenNamesField;
            }
            set
            {
                this.givenNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NameType
        {
            get
            {
                return this.nameTypeField;
            }
            set
            {
                this.nameTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public enum Gender
    {

        /// <remarks/>
        NotSpecified,

        /// <remarks/>
        Indeterminate,

        /// <remarks/>
        Male,

        /// <remarks/>
        Female,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Dealing
    {

        private string dealingNumberField;

        private string titleReferenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DealingNumber
        {
            get
            {
                return this.dealingNumberField;
            }
            set
            {
                this.dealingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TitleReference
        {
            get
            {
                return this.titleReferenceField;
            }
            set
            {
                this.titleReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Company))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Organisation : Entity
    {

        private string aBNField;

        private string aRBNField;

        private string aRSNField;

        private string nameField;

        private OrganisationName[] otherNamesField;

        private string statusField;

        private Region registrationRegionField;

        private Address[] addressesField;

        private ContactDetails[] contactDetailsField;

        private string organisationTypeField;

        private string previousStateNumberField;

        public Organisation()
        {
            this.registrationRegionField = Region.Unknown;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string ABN
        {
            get
            {
                return this.aBNField;
            }
            set
            {
                this.aBNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string ARBN
        {
            get
            {
                return this.aRBNField;
            }
            set
            {
                this.aRBNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string ARSN
        {
            get
            {
                return this.aRSNField;
            }
            set
            {
                this.aRSNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 4)]
        public OrganisationName[] OtherNames
        {
            get
            {
                return this.otherNamesField;
            }
            set
            {
                this.otherNamesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public Region RegistrationRegion
        {
            get
            {
                return this.registrationRegionField;
            }
            set
            {
                this.registrationRegionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 7)]
        public Address[] Addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 8)]
        public ContactDetails[] ContactDetails
        {
            get
            {
                return this.contactDetailsField;
            }
            set
            {
                this.contactDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 9)]
        public string OrganisationType
        {
            get
            {
                return this.organisationTypeField;
            }
            set
            {
                this.organisationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 10)]
        public string PreviousStateNumber
        {
            get
            {
                return this.previousStateNumberField;
            }
            set
            {
                this.previousStateNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class OrganisationName
    {

        private string nameTypeField;

        private string nameField;

        private System.Nullable<System.DateTime> startDateField;

        private System.Nullable<System.DateTime> endDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NameType
        {
            get
            {
                return this.nameTypeField;
            }
            set
            {
                this.nameTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public enum Region
    {

        /// <remarks/>
        Unknown,

        /// <remarks/>
        Australia,

        /// <remarks/>
        NSW,

        /// <remarks/>
        QLD,

        /// <remarks/>
        Vic,

        /// <remarks/>
        Tas,

        /// <remarks/>
        ACT,

        /// <remarks/>
        WA,

        /// <remarks/>
        NT,

        /// <remarks/>
        SA,

        /// <remarks/>
        NZ,

        /// <remarks/>
        International,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Company : Organisation
    {

        private string aCNField;

        private string aSXCodeField;

        private CompanyDetails companyDetailsField;

        private CompanyDetails[] historicDetailsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string ACN
        {
            get
            {
                return this.aCNField;
            }
            set
            {
                this.aCNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string ASXCode
        {
            get
            {
                return this.aSXCodeField;
            }
            set
            {
                this.aSXCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public CompanyDetails CompanyDetails
        {
            get
            {
                return this.companyDetailsField;
            }
            set
            {
                this.companyDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true, Order = 3)]
        public CompanyDetails[] HistoricDetails
        {
            get
            {
                return this.historicDetailsField;
            }
            set
            {
                this.historicDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class CompanyDetails
    {

        private System.Nullable<System.DateTime> startDateField;

        private System.Nullable<System.DateTime> endDateField;

        private string statusField;

        private OrganisationName nameField;

        private string companyTypeField;

        private string companyClassField;

        private string companySubclassField;

        private System.Nullable<bool> disclosingEntityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public OrganisationName Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CompanyType
        {
            get
            {
                return this.companyTypeField;
            }
            set
            {
                this.companyTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CompanyClass
        {
            get
            {
                return this.companyClassField;
            }
            set
            {
                this.companyClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CompanySubclass
        {
            get
            {
                return this.companySubclassField;
            }
            set
            {
                this.companySubclassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> DisclosingEntity
        {
            get
            {
                return this.disclosingEntityField;
            }
            set
            {
                this.disclosingEntityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
    public partial class Settlement : Entity
    {

        private string settlementTypeField;

        private System.Nullable<System.DateTime> settlementTimeField;

        private bool settlementTimeFieldSpecified;

        private System.Nullable<float> purchasePriceField;

        private bool purchasePriceFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string SettlementType
        {
            get
            {
                return this.settlementTypeField;
            }
            set
            {
                this.settlementTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public System.Nullable<System.DateTime> SettlementTime
        {
            get
            {
                return this.settlementTimeField;
            }
            set
            {
                this.settlementTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SettlementTimeSpecified
        {
            get
            {
                return this.settlementTimeFieldSpecified;
            }
            set
            {
                this.settlementTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public System.Nullable<float> PurchasePrice
        {
            get
            {
                return this.purchasePriceField;
            }
            set
            {
                this.purchasePriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PurchasePriceSpecified
        {
            get
            {
                return this.purchasePriceFieldSpecified;
            }
            set
            {
                this.purchasePriceFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://globalx.com.au/common/model/cdmpayload/2013/07/31")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://globalx.com.au/common/model/cdmpayload/2013/07/31", IsNullable = false)]
    public partial class CdmPayload
    {

        private Entity[] entitiesField;

        private Relationship[] linkedEntitiesField;

        private Datum[] factsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
        public Entity[] Entities
        {
            get
            {
                return this.entitiesField;
            }
            set
            {
                this.entitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
        public Relationship[] LinkedEntities
        {
            get
            {
                return this.linkedEntitiesField;
            }
            set
            {
                this.linkedEntitiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://globalx.com.au/common/model/2013/07/31")]
        public Datum[] Facts
        {
            get
            {
                return this.factsField;
            }
            set
            {
                this.factsField = value;
            }
        }
    }
}
