
export const GET_ACCOUNT_INFO_REQUESTED = "CommonReducer/GET_ACCOUNT_INFO_REQUESTED"
export const GET_ACCOUNT_INFO_SUCCESS = "CommonReducer/GET_ACCOUNT_INFO_SUCCESS"
export const GET_ACCOUNT_INFO_FAILED = "CommonReducer/GET_ACCOUNT_INFO_FAILED"

export const SET_UI_DEFINITIONS = "CommonReducer/SET_UI_DEFINITIONS"

export const GET_MATTER_INFO_REQUESTED = "CommonReducer/GET_MATTER_INFO_REQUESTED"
export const GET_MATTER_INFO_SUCCESS = "CommonReducer/GET_MATTER_INFO_SUCCESS"
export const GET_MATTER_INFO_FAILED = "CommonReducer/GET_MATTER_INFO_FAILED"

export const LOG_AUTH_FAILURE = "CommonReducer/LOG_AUTH_FAILURE"

export const SET_JWT_MATTER_INFO = "CommonReducer/SET_JWT_MATTER_INFO"

export const ACTIONSTEP_ORG_NOT_CONNECTED = "CommonReducer/ACTIONSTEP_ORG_NOT_CONNECTED"
export const ACTIONSTEP_ORG_CONNECTED = "CommonReducer/ACTIONSTEP_ORG_CONNECTED"

export const PEXA_NOT_CONNECTED = "CommonReducer/PEXA_NOT_CONNECTED"
export const PEXA_CONNECTED = "CommonReducer/PEXA_CONNECTED"

export const FIRST_TITLE_NOT_CONNECTED = "CommonReducer/FIRST_TITLE_NOT_CONNECTED"
export const FIRST_TITLE_CONNECTED = "CommonReducer/FIRST_TITLE_CONNECTED"

export const CLEAR_COMMON_STATE = "CommonReducer/CLEAR_COMMON_STATE"
